spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beneficiaries
    username: ekan@2319!
    password: ekan@2319!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  packages-to-scan: com.ekan.ekanproject.application.rest
  enable-data-rest: false
